name: Java 25

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Azul JDK 25
        uses: actions/setup-java@v3
        with:
          java-version: 25
          distribution: 'zulu'
          cache: 'maven'
      - name: Test in Maven
        run: mvn test
